#!/bin/bash

set -e

if [ -z "$PHP_VERSION" ]; then
  echo -e "\e[00;31mError: Must set PHP_VERSION, i.e PHP_VERSION=5.4.14"
  exit 1
fi

if [[ -z "$BUILDPACK_CACHE" ]]; then
  echo -e "\e[00;31mError: Must pass a valid BUILDPACK_CACHE - eg: BUILDPACK_CACHE=~/.buildpack-cache"
  exit 1
fi

sudo apt-get install libcurl4-openssl-dev pkg-config libbz2-dev libjpeg-dev libpng-dev -y

#ensure a clean compile location
rm -rf /app/runtimes/nginx

basedir="$( cd -P "$( dirname "$0" )" && pwd )"

# make a temp directory
tempdir="$( mktemp -t php_XXXX )"
rm -rf $tempdir
mkdir -p $tempdir
pushd $tempdir

# download and extract php
curl -L http://uk3.php.net/get/php-$PHP_VERSION.tar.gz/from/uk1.php.net/mirror -o php.tar.gz
tar xzvf php.tar.gz

# build and package nginx 
pushd $tempdir/php-$PHP_VERSION
./configure  --prefix=/app/runtimes/php \
                --with-mysql \
                --with-pdo-mysql \
                --with-iconv \
                --with-gd \
                --with-curl=/usr/lib \
                --with-config-file-path=/app/runtimes/php \
                --with-openssl \
                --with-zlib \
                --enable-mbstring \
                --disable-debug \
                --disable-rpath \
                --enable-gd-native-ttf \
                --enable-inline-optimization \
                --with-bz2 \
                --enable-pcntl \
                --enable-mbregex \
                --with-mhash \
                --enable-zip \
                --with-pcre-regex \
                --enable-libxml \
                --with-gettext \
                --with-jpeg-dir \
                --with-mysqli \
                --with-pcre-regex \
                --with-png-dir \
                --without-pdo-sqlite \
                --without-sqlite3 \
                && make install \
                && /app/runtimes/php/bin/pear config-set php_dir /app/runtimes/php \
                && yes '' | /app/runtimes/php/bin/pecl install xdebug 
popd
tar --transform='s,^app/runtimes/,,' -czf php-$PHP_VERSION.tar.gz /app/runtimes/php/

mv $(pwd)/php-$PHP_VERSION.tar.gz ${BUILDPACK_CACHE}

echo "Successfully finished building php to ${BUILDPACK_CACHE}/php-$PHP_VERSION.tar.gz"

