#!/bin/bash
echo "This is a work in progress, and doesn't currently work :("

exit 1

sudo apt-get update 
sudo apt-get purge libboost*1.46* -y
sudo apt-get install git-core cmake g++ libboost1.48-all-dev libmysqlclient-dev \
  libxml2-dev libmcrypt-dev libicu-dev openssl build-essential binutils-dev \
  libcap-dev libgd2-xpm-dev zlib1g-dev libtbb-dev libonig-dev libpcre3-dev \
  autoconf libtool libcurl4-openssl-dev \
  wget memcached \
  libreadline-dev libncurses-dev libmemcached-dev libbz2-dev \
  libc-client2007e-dev php5-mcrypt php5-imagick libgoogle-perftools-dev \
  libcloog-ppl0 libelf-dev libdwarf-dev libunwind7-dev subversion -y

basedir="$( cd -P "$( dirname "$0" )" && pwd )"

# make a temp directory
tempdir="$( mktemp -t hiphop_XXXX )"
rm -rf $tempdir
mkdir -p $tempdir
cd $tempdir

git clone git://github.com/facebook/hiphop-php.git
cd hiphop-php
export CMAKE_PREFIX_PATH=`pwd`/..
export HPHP_HOME=`pwd`
export HPHP_LIB=`pwd`/bin
export USE_HHVM=1
cd ..

git clone git://github.com/libevent/libevent.git
cd libevent
git checkout release-1.4.14b-stable
cat ../hiphop-php/hphp/third_party/libevent-1.4.14.fb-changes.diff | patch -p1
./autogen.sh
./configure --prefix=$CMAKE_PREFIX_PATH
make
make install
cd ..

git clone git://github.com/bagder/curl.git
cd curl
./buildconf
./configure --prefix=$CMAKE_PREFIX_PATH
make
make install
cd ..

svn checkout http://google-glog.googlecode.com/svn/trunk/ google-glog
cd google-glog
./configure --prefix=$CMAKE_PREFIX_PATH
make
make install
cd ..

wget http://www.canonware.com/download/jemalloc/jemalloc-3.0.0.tar.bz2
tar xjvf jemalloc-3.0.0.tar.bz2
cd jemalloc-3.0.0
./configure --prefix=$CMAKE_PREFIX_PATH
make
make install
cd ..

cd hiphop-php
git submodule init
git submodule update
export HPHP_HOME=`pwd`
export HPHP_LIB=`pwd`/bin
cmake .
make

##

PACKAGE_DIR=/tmp/hiphop-php
echo "-----> Collecting hiphop files into ${PACKAGE_DIR}"
cd $tempdir

mkdir -p ${PACKAGE_DIR}/lib
cp -a lib/* ${PACKAGE_DIR}/lib

cp -a /usr/lib/libicudata.so.48* ${PACKAGE_DIR}/lib
cp -a /usr/lib/libc-client.so.2007e* ${PACKAGE_DIR}/lib
cp -a /usr/lib/libboost_regex.so.1.48.0 ${PACKAGE_DIR}/lib
cp -a /usr/lib/libboost_filesystem.so.1.48.0 ${PACKAGE_DIR}/lib
cp -a /usr/lib/libboost_program_options.so.1.48.0 ${PACKAGE_DIR}/lib
cp -a /usr/lib/libboost_system.so.1.48.0 ${PACKAGE_DIR}/lib
cp -a /usr/lib/libmemcached.so.6* ${PACKAGE_DIR}/lib
cp -a /usr/lib/libmcrypt.so.4* ${PACKAGE_DIR}/lib
cp -a /usr/lib/libonig.so.2* ${PACKAGE_DIR}/lib
cp -a /usr/lib/libtbb.so.2* ${PACKAGE_DIR}/lib
cp -a /usr/lib/libbfd-2.22-system.so* ${PACKAGE_DIR}/lib
cp -a /usr/lib/libicui18n.so.48* ${PACKAGE_DIR}/lib
cp -a /usr/lib/libicuuc.so.48* ${PACKAGE_DIR}/lib
cp -a /usr/lib/libunwind* ${PACKAGE_DIR}/lib

mkdir ${PACKAGE_DIR}/lib/x86_64-linux-gnu
cp -a /usr/lib/x86_64-linux-gnu/libmysqlclient.so.18*	 ${PACKAGE_DIR}/lib/x86_64-linux-gnu
cp -a /usr/lib/x86_64-linux-gnu/libxml2.so.2*					 ${PACKAGE_DIR}/lib/x86_64-linux-gnu
cp -a /usr/lib/x86_64-linux-gnu/libgd.so.2*						 ${PACKAGE_DIR}/lib/x86_64-linux-gnu
cp -a /usr/lib/x86_64-linux-gnu/libldap_r-2.4.so.2*		 ${PACKAGE_DIR}/lib/x86_64-linux-gnu
cp -a /usr/lib/x86_64-linux-gnu/liblber-2.4.so.2*			 ${PACKAGE_DIR}/lib/x86_64-linux-gnu
cp -a /usr/lib/x86_64-linux-gnu/libelf.so.1*					 ${PACKAGE_DIR}/lib/x86_64-linux-gnu
cp -a /usr/lib/x86_64-linux-gnu/libelf-0.152.so*			 ${PACKAGE_DIR}/lib/x86_64-linux-gnu
cp -a /usr/lib/x86_64-linux-gnu/libstdc++.so.6*				 ${PACKAGE_DIR}/lib/x86_64-linux-gnu
cp -a /usr/lib/x86_64-linux-gnu/libidn.so.11*					 ${PACKAGE_DIR}/lib/x86_64-linux-gnu
cp -a /usr/lib/x86_64-linux-gnu/librtmp.so.0*					 ${PACKAGE_DIR}/lib/x86_64-linux-gnu
cp -a /usr/lib/x86_64-linux-gnu/libXpm.so.4*					 ${PACKAGE_DIR}/lib/x86_64-linux-gnu
cp -a /usr/lib/x86_64-linux-gnu/libjpeg.so.8*					 ${PACKAGE_DIR}/lib/x86_64-linux-gnu
cp -a /usr/lib/x86_64-linux-gnu/libfontconfig.so.1*		 ${PACKAGE_DIR}/lib/x86_64-linux-gnu
cp -a /usr/lib/x86_64-linux-gnu/libfreetype.so.6*			 ${PACKAGE_DIR}/lib/x86_64-linux-gnu
cp -a /usr/lib/x86_64-linux-gnu/libsasl2.so.2*				 ${PACKAGE_DIR}/lib/x86_64-linux-gnu
cp -a /usr/lib/x86_64-linux-gnu/libgssapi.so.3*				 ${PACKAGE_DIR}/lib/x86_64-linux-gnu
cp -a /usr/lib/x86_64-linux-gnu/libgnutls.so.26*			 ${PACKAGE_DIR}/lib/x86_64-linux-gnu
cp -a /usr/lib/x86_64-linux-gnu/libgssapi_krb5.so.2*	 ${PACKAGE_DIR}/lib/x86_64-linux-gnu
cp -a /usr/lib/x86_64-linux-gnu/libkrb5.so.3*					 ${PACKAGE_DIR}/lib/x86_64-linux-gnu
cp -a /usr/lib/x86_64-linux-gnu/libX11.so.6*					 ${PACKAGE_DIR}/lib/x86_64-linux-gnu
cp -a /usr/lib/x86_64-linux-gnu/libheimntlm.so.0*			 ${PACKAGE_DIR}/lib/x86_64-linux-gnu
cp -a /usr/lib/x86_64-linux-gnu/libkrb5.so.26*				 ${PACKAGE_DIR}/lib/x86_64-linux-gnu
cp -a /usr/lib/x86_64-linux-gnu/libasn1.so.8*					 ${PACKAGE_DIR}/lib/x86_64-linux-gnu
cp -a /usr/lib/x86_64-linux-gnu/libhcrypto.so.4*			 ${PACKAGE_DIR}/lib/x86_64-linux-gnu
cp -a /usr/lib/x86_64-linux-gnu/libroken.so.18*				 ${PACKAGE_DIR}/lib/x86_64-linux-gnu
cp -a /usr/lib/x86_64-linux-gnu/libtasn1.so.3*				 ${PACKAGE_DIR}/lib/x86_64-linux-gnu
cp -a /usr/lib/x86_64-linux-gnu/libp11-kit.so.0*			 ${PACKAGE_DIR}/lib/x86_64-linux-gnu
cp -a /usr/lib/x86_64-linux-gnu/libk5crypto.so.3*			 ${PACKAGE_DIR}/lib/x86_64-linux-gnu
cp -a /usr/lib/x86_64-linux-gnu/libkrb5support.so.0*	 ${PACKAGE_DIR}/lib/x86_64-linux-gnu
cp -a /usr/lib/x86_64-linux-gnu/libxcb.so.1*					 ${PACKAGE_DIR}/lib/x86_64-linux-gnu
cp -a /usr/lib/x86_64-linux-gnu/libwind.so.0*					 ${PACKAGE_DIR}/lib/x86_64-linux-gnu
cp -a /usr/lib/x86_64-linux-gnu/libheimbase.so.1*			 ${PACKAGE_DIR}/lib/x86_64-linux-gnu
cp -a /usr/lib/x86_64-linux-gnu/libhx509.so.5*				 ${PACKAGE_DIR}/lib/x86_64-linux-gnu
cp -a /usr/lib/x86_64-linux-gnu/libsqlite3.so.0*			 ${PACKAGE_DIR}/lib/x86_64-linux-gnu
cp -a /usr/lib/x86_64-linux-gnu/libXau.so.6*					 ${PACKAGE_DIR}/lib/x86_64-linux-gnu
cp -a /usr/lib/x86_64-linux-gnu/libXdmcp.so.6*				 ${PACKAGE_DIR}/lib/x86_64-linux-gnu
cp -a /lib/x86_64-linux-gnu/libpcre.so.3*						   ${PACKAGE_DIR}/lib/x86_64-linux-gnu
cp -a /lib/x86_64-linux-gnu/libcap.so.2*					 		 ${PACKAGE_DIR}/lib/x86_64-linux-gnu
cp -a /lib/x86_64-linux-gnu/libresolv.so.2*						 ${PACKAGE_DIR}/lib/x86_64-linux-gnu
cp -a /lib/x86_64-linux-gnu/libresolv-2.15.so*				 ${PACKAGE_DIR}/lib/x86_64-linux-gnu
cp -a /lib/x86_64-linux-gnu/libdl.so.2*						 		 ${PACKAGE_DIR}/lib/x86_64-linux-gnu
cp -a /lib/x86_64-linux-gnu/libdl-2.15.so*				 		 ${PACKAGE_DIR}/lib/x86_64-linux-gnu
cp -a /lib/x86_64-linux-gnu/libssl.so.1.0.0*					 ${PACKAGE_DIR}/lib/x86_64-linux-gnu
cp -a /lib/x86_64-linux-gnu/libcrypto.so.1.0.0*				 ${PACKAGE_DIR}/lib/x86_64-linux-gnu
cp -a /lib/x86_64-linux-gnu/libz.so.1*					 			 ${PACKAGE_DIR}/lib/x86_64-linux-gnu
cp -a /lib/x86_64-linux-gnu/libbz2.so.1.0*					 	 ${PACKAGE_DIR}/lib/x86_64-linux-gnu
cp -a /lib/x86_64-linux-gnu/libexpat.so.1*					 	 ${PACKAGE_DIR}/lib/x86_64-linux-gnu
cp -a /lib/x86_64-linux-gnu/libpthread.so.0*					 ${PACKAGE_DIR}/lib/x86_64-linux-gnu
cp -a /lib/x86_64-linux-gnu/libpthread-2.15.so*				 ${PACKAGE_DIR}/lib/x86_64-linux-gnu
cp -a /lib/x86_64-linux-gnu/libcrypt.so.1*					 	 ${PACKAGE_DIR}/lib/x86_64-linux-gnu
cp -a /lib/x86_64-linux-gnu/librt.so.1*						 		 ${PACKAGE_DIR}/lib/x86_64-linux-gnu
cp -a /lib/x86_64-linux-gnu/librt-2.15.so*				 		 ${PACKAGE_DIR}/lib/x86_64-linux-gnu
cp -a /lib/x86_64-linux-gnu/libcrypt-2.15.so*			 		 ${PACKAGE_DIR}/lib/x86_64-linux-gnu
cp -a /lib/x86_64-linux-gnu/libreadline.so.6*					 ${PACKAGE_DIR}/lib/x86_64-linux-gnu
cp -a /lib/x86_64-linux-gnu/libm.so.6*					 			 ${PACKAGE_DIR}/lib/x86_64-linux-gnu
cp -a /lib/x86_64-linux-gnu/libm-2.15.so*				 			 ${PACKAGE_DIR}/lib/x86_64-linux-gnu
cp -a /lib/x86_64-linux-gnu/libgcc_s.so.1*					 	 ${PACKAGE_DIR}/lib/x86_64-linux-gnu
cp -a /lib/x86_64-linux-gnu/libc.so.6*					 			 ${PACKAGE_DIR}/lib/x86_64-linux-gnu
cp -a /lib/x86_64-linux-gnu/libc-2.15.so*				 			 ${PACKAGE_DIR}/lib/x86_64-linux-gnu
cp -a /lib/x86_64-linux-gnu/libpng12.so.0*					 	 ${PACKAGE_DIR}/lib/x86_64-linux-gnu
cp -a /lib/x86_64-linux-gnu/libgcrypt.so.11*					 ${PACKAGE_DIR}/lib/x86_64-linux-gnu
cp -a /lib/x86_64-linux-gnu/libtinfo.so.5*					   ${PACKAGE_DIR}/lib/x86_64-linux-gnu
cp -a /lib/x86_64-linux-gnu/libpam.so.0*					 		 ${PACKAGE_DIR}/lib/x86_64-linux-gnu
cp -a /lib/x86_64-linux-gnu/libcom_err.so.2*					 ${PACKAGE_DIR}/lib/x86_64-linux-gnu
cp -a /lib/x86_64-linux-gnu/libgpg-error.so.0*				 ${PACKAGE_DIR}/lib/x86_64-linux-gnu
cp -a /lib/x86_64-linux-gnu/libkeyutils.so.1*					 ${PACKAGE_DIR}/lib/x86_64-linux-gnu

mkdir ${PACKAGE_DIR}/bin
cp hiphop-php/bin/systemlib.php ${PACKAGE_DIR}/bin
cp hiphop-php/hphp/hhvm/hhvm ${PACKAGE_DIR}/bin

#cp hiphop-php/hphp/hhvm/mlock ${PACKAGE_DIR}/bin/

tree ${PACKAGE_DIR}

echo "-----> Creating archive: hiphop-php-2.1.0-dev.tar.gz"
tar --transform='s,^tmp/,,' -czf hiphop-php-2.1.0-dev.tar.gz ${PACKAGE_DIR}/