#!/bin/bash
if [[ -z "$BUILDPACK_CACHE" ]]; then
  echo -e "\e[00;31mError: Must pass a valid BUILDPACK_CACHE - eg: BUILDPACK_CACHE=/app/.buildpack-cache"
  exit 1
fi

HIPHOP_SHA=56172bc9fca251456620584be4959f1d333bf851

sudo apt-get update 
sudo apt-get purge libboost*1.46* -y

basedir="$( cd -P "$( dirname "$0" )" && pwd )"

# make a temp directory
tempdir="$( mktemp -t hiphop_XXXX )"
rm -rf $tempdir
mkdir -p $tempdir
cd $tempdir

git clone git://github.com/facebook/hiphop-php.git
cd hiphop-php
git checkout ${HIPHOP_SHA} --force
git submodule init
git submodule update

./configure_ubuntu_12.04.sh 

HPHP_HOME=`pwd` make -j 8

##

PACKAGE_DIR=/tmp/hiphop-php
echo "-----> Collecting hiphop files into ${PACKAGE_DIR}"
cd $tempdir

mkdir -p ${PACKAGE_DIR}/lib
cp -a lib/* ${PACKAGE_DIR}/lib

cp -a /usr/lib/libicudata.so.48* ${PACKAGE_DIR}/lib
cp -a /usr/lib/libc-client.so.2007e* ${PACKAGE_DIR}/lib
cp -a /usr/lib/libboost_regex.so.1.48.0 ${PACKAGE_DIR}/lib
cp -a /usr/lib/libboost_filesystem.so.1.48.0 ${PACKAGE_DIR}/lib
cp -a /usr/lib/libboost_program_options.so.1.48.0 ${PACKAGE_DIR}/lib
cp -a /usr/lib/libboost_system.so.1.48.0 ${PACKAGE_DIR}/lib
cp -a /usr/lib/libmemcached.so.6* ${PACKAGE_DIR}/lib
cp -a /usr/lib/libmcrypt.so.4* ${PACKAGE_DIR}/lib
cp -a /usr/lib/libonig.so.2* ${PACKAGE_DIR}/lib
cp -a /usr/lib/libtbb.so.2* ${PACKAGE_DIR}/lib
cp -a /usr/lib/libbfd-2.22-system.so* ${PACKAGE_DIR}/lib
cp -a /usr/lib/libicui18n.so.48* ${PACKAGE_DIR}/lib
cp -a /usr/lib/libicuuc.so.48* ${PACKAGE_DIR}/lib
cp -a /usr/lib/libunwind* ${PACKAGE_DIR}/lib

mkdir ${PACKAGE_DIR}/lib/x86_64-linux-gnu
cp -a /usr/lib/x86_64-linux-gnu/libmysqlclient.so.18*	 ${PACKAGE_DIR}/lib/x86_64-linux-gnu
cp -a /usr/lib/x86_64-linux-gnu/libxml2.so.2*					 ${PACKAGE_DIR}/lib/x86_64-linux-gnu
cp -a /usr/lib/x86_64-linux-gnu/libgd.so.2*						 ${PACKAGE_DIR}/lib/x86_64-linux-gnu
cp -a /usr/lib/x86_64-linux-gnu/libldap_r-2.4.so.2*		 ${PACKAGE_DIR}/lib/x86_64-linux-gnu
cp -a /usr/lib/x86_64-linux-gnu/liblber-2.4.so.2*			 ${PACKAGE_DIR}/lib/x86_64-linux-gnu
cp -a /usr/lib/x86_64-linux-gnu/libelf.so.1*					 ${PACKAGE_DIR}/lib/x86_64-linux-gnu
cp -a /usr/lib/x86_64-linux-gnu/libelf-0.152.so*			 ${PACKAGE_DIR}/lib/x86_64-linux-gnu
cp -a /usr/lib/x86_64-linux-gnu/libstdc++.so.6*				 ${PACKAGE_DIR}/lib/x86_64-linux-gnu
cp -a /usr/lib/x86_64-linux-gnu/libidn.so.11*					 ${PACKAGE_DIR}/lib/x86_64-linux-gnu
cp -a /usr/lib/x86_64-linux-gnu/librtmp.so.0*					 ${PACKAGE_DIR}/lib/x86_64-linux-gnu
cp -a /usr/lib/x86_64-linux-gnu/libXpm.so.4*					 ${PACKAGE_DIR}/lib/x86_64-linux-gnu
cp -a /usr/lib/x86_64-linux-gnu/libjpeg.so.8*					 ${PACKAGE_DIR}/lib/x86_64-linux-gnu
cp -a /usr/lib/x86_64-linux-gnu/libfontconfig.so.1*		 ${PACKAGE_DIR}/lib/x86_64-linux-gnu
cp -a /usr/lib/x86_64-linux-gnu/libfreetype.so.6*			 ${PACKAGE_DIR}/lib/x86_64-linux-gnu
cp -a /usr/lib/x86_64-linux-gnu/libsasl2.so.2*				 ${PACKAGE_DIR}/lib/x86_64-linux-gnu
cp -a /usr/lib/x86_64-linux-gnu/libgssapi.so.3*				 ${PACKAGE_DIR}/lib/x86_64-linux-gnu
cp -a /usr/lib/x86_64-linux-gnu/libgnutls.so.26*			 ${PACKAGE_DIR}/lib/x86_64-linux-gnu
cp -a /usr/lib/x86_64-linux-gnu/libgssapi_krb5.so.2*	 ${PACKAGE_DIR}/lib/x86_64-linux-gnu
cp -a /usr/lib/x86_64-linux-gnu/libkrb5.so.3*					 ${PACKAGE_DIR}/lib/x86_64-linux-gnu
cp -a /usr/lib/x86_64-linux-gnu/libX11.so.6*					 ${PACKAGE_DIR}/lib/x86_64-linux-gnu
cp -a /usr/lib/x86_64-linux-gnu/libheimntlm.so.0*			 ${PACKAGE_DIR}/lib/x86_64-linux-gnu
cp -a /usr/lib/x86_64-linux-gnu/libkrb5.so.26*				 ${PACKAGE_DIR}/lib/x86_64-linux-gnu
cp -a /usr/lib/x86_64-linux-gnu/libasn1.so.8*					 ${PACKAGE_DIR}/lib/x86_64-linux-gnu
cp -a /usr/lib/x86_64-linux-gnu/libhcrypto.so.4*			 ${PACKAGE_DIR}/lib/x86_64-linux-gnu
cp -a /usr/lib/x86_64-linux-gnu/libroken.so.18*				 ${PACKAGE_DIR}/lib/x86_64-linux-gnu
cp -a /usr/lib/x86_64-linux-gnu/libtasn1.so.3*				 ${PACKAGE_DIR}/lib/x86_64-linux-gnu
cp -a /usr/lib/x86_64-linux-gnu/libp11-kit.so.0*			 ${PACKAGE_DIR}/lib/x86_64-linux-gnu
cp -a /usr/lib/x86_64-linux-gnu/libk5crypto.so.3*			 ${PACKAGE_DIR}/lib/x86_64-linux-gnu
cp -a /usr/lib/x86_64-linux-gnu/libkrb5support.so.0*	 ${PACKAGE_DIR}/lib/x86_64-linux-gnu
cp -a /usr/lib/x86_64-linux-gnu/libxcb.so.1*					 ${PACKAGE_DIR}/lib/x86_64-linux-gnu
cp -a /usr/lib/x86_64-linux-gnu/libwind.so.0*					 ${PACKAGE_DIR}/lib/x86_64-linux-gnu
cp -a /usr/lib/x86_64-linux-gnu/libheimbase.so.1*			 ${PACKAGE_DIR}/lib/x86_64-linux-gnu
cp -a /usr/lib/x86_64-linux-gnu/libhx509.so.5*				 ${PACKAGE_DIR}/lib/x86_64-linux-gnu
cp -a /usr/lib/x86_64-linux-gnu/libsqlite3.so.0*			 ${PACKAGE_DIR}/lib/x86_64-linux-gnu
cp -a /usr/lib/x86_64-linux-gnu/libXau.so.6*					 ${PACKAGE_DIR}/lib/x86_64-linux-gnu
cp -a /usr/lib/x86_64-linux-gnu/libXdmcp.so.6*				 ${PACKAGE_DIR}/lib/x86_64-linux-gnu
cp -a /lib/x86_64-linux-gnu/libpcre.so.3*						   ${PACKAGE_DIR}/lib/x86_64-linux-gnu
cp -a /lib/x86_64-linux-gnu/libcap.so.2*					 		 ${PACKAGE_DIR}/lib/x86_64-linux-gnu
cp -a /lib/x86_64-linux-gnu/libresolv.so.2*						 ${PACKAGE_DIR}/lib/x86_64-linux-gnu
cp -a /lib/x86_64-linux-gnu/libresolv-2.15.so*				 ${PACKAGE_DIR}/lib/x86_64-linux-gnu
cp -a /lib/x86_64-linux-gnu/libdl.so.2*						 		 ${PACKAGE_DIR}/lib/x86_64-linux-gnu
cp -a /lib/x86_64-linux-gnu/libdl-2.15.so*				 		 ${PACKAGE_DIR}/lib/x86_64-linux-gnu
cp -a /lib/x86_64-linux-gnu/libssl.so.1.0.0*					 ${PACKAGE_DIR}/lib/x86_64-linux-gnu
cp -a /lib/x86_64-linux-gnu/libcrypto.so.1.0.0*				 ${PACKAGE_DIR}/lib/x86_64-linux-gnu
cp -a /lib/x86_64-linux-gnu/libz.so.1*					 			 ${PACKAGE_DIR}/lib/x86_64-linux-gnu
cp -a /lib/x86_64-linux-gnu/libbz2.so.1.0*					 	 ${PACKAGE_DIR}/lib/x86_64-linux-gnu
cp -a /lib/x86_64-linux-gnu/libexpat.so.1*					 	 ${PACKAGE_DIR}/lib/x86_64-linux-gnu
cp -a /lib/x86_64-linux-gnu/libpthread.so.0*					 ${PACKAGE_DIR}/lib/x86_64-linux-gnu
cp -a /lib/x86_64-linux-gnu/libpthread-2.15.so*				 ${PACKAGE_DIR}/lib/x86_64-linux-gnu
cp -a /lib/x86_64-linux-gnu/libcrypt.so.1*					 	 ${PACKAGE_DIR}/lib/x86_64-linux-gnu
cp -a /lib/x86_64-linux-gnu/librt.so.1*						 		 ${PACKAGE_DIR}/lib/x86_64-linux-gnu
cp -a /lib/x86_64-linux-gnu/librt-2.15.so*				 		 ${PACKAGE_DIR}/lib/x86_64-linux-gnu
cp -a /lib/x86_64-linux-gnu/libcrypt-2.15.so*			 		 ${PACKAGE_DIR}/lib/x86_64-linux-gnu
cp -a /lib/x86_64-linux-gnu/libreadline.so.6*					 ${PACKAGE_DIR}/lib/x86_64-linux-gnu
cp -a /lib/x86_64-linux-gnu/libm.so.6*					 			 ${PACKAGE_DIR}/lib/x86_64-linux-gnu
cp -a /lib/x86_64-linux-gnu/libm-2.15.so*				 			 ${PACKAGE_DIR}/lib/x86_64-linux-gnu
cp -a /lib/x86_64-linux-gnu/libgcc_s.so.1*					 	 ${PACKAGE_DIR}/lib/x86_64-linux-gnu
cp -a /lib/x86_64-linux-gnu/libc.so.6*					 			 ${PACKAGE_DIR}/lib/x86_64-linux-gnu
cp -a /lib/x86_64-linux-gnu/libc-2.15.so*				 			 ${PACKAGE_DIR}/lib/x86_64-linux-gnu
cp -a /lib/x86_64-linux-gnu/libpng12.so.0*					 	 ${PACKAGE_DIR}/lib/x86_64-linux-gnu
cp -a /lib/x86_64-linux-gnu/libgcrypt.so.11*					 ${PACKAGE_DIR}/lib/x86_64-linux-gnu
cp -a /lib/x86_64-linux-gnu/libtinfo.so.5*					   ${PACKAGE_DIR}/lib/x86_64-linux-gnu
cp -a /lib/x86_64-linux-gnu/libpam.so.0*					 		 ${PACKAGE_DIR}/lib/x86_64-linux-gnu
cp -a /lib/x86_64-linux-gnu/libcom_err.so.2*					 ${PACKAGE_DIR}/lib/x86_64-linux-gnu
cp -a /lib/x86_64-linux-gnu/libgpg-error.so.0*				 ${PACKAGE_DIR}/lib/x86_64-linux-gnu
cp -a /lib/x86_64-linux-gnu/libkeyutils.so.1*					 ${PACKAGE_DIR}/lib/x86_64-linux-gnu

mkdir ${PACKAGE_DIR}/bin
cp hiphop-php/bin/systemlib.php ${PACKAGE_DIR}/bin
cp hiphop-php/hphp/hhvm/hhvm ${PACKAGE_DIR}/bin

#cp hiphop-php/hphp/hhvm/mlock ${PACKAGE_DIR}/bin/

tree ${PACKAGE_DIR}

echo "-----> Creating archive: hiphop-php-2.1.0-${HIPHOP_SHA}.tar.gz"
tar --transform='s,^tmp/,,' -czf hiphop-php-2.1.0-${HIPHOP_SHA}.tar.gz ${PACKAGE_DIR}/

mv $(pwd)/hiphop-php-2.1.0-${HIPHOP_SHA}.tar.gz ${BUILDPACK_CACHE}

echo "Successfully finished building nginx to ${BUILDPACK_CACHE}/hiphop-php-2.1.0-${HIPHOP_SHA}.tar.gz"