#!/bin/bash

if [ ! -f /usr/bin/hhvm ]; then
  echo "Installing hiphop"
  echo "deb http://dl.hiphop-php.com/ubuntu precise main" | sudo tee -a /etc/apt/sources.list
  sudo apt-get update
  sudo apt-get install hiphop-php tree -y --force-yes
fi
echo "-----> Using: $(hhvm --version)" | head -n 1

basedir="$( cd -P "$( dirname "$0" )" && pwd )"

# make a temp directory
tempdir=/tmp/hiphop-php
rm -rf $tempdir
mkdir -p $tempdir

echo "-----> Collecting hiphop files into $tempdir"

cp -Rf /usr/hiphop-php/* $tempdir
cp -Rf /usr/share/hiphop-php/* $tempdir
cp -a /usr/lib/libboost_filesystem.so.1.48.0 $tempdir/lib
cp -a /usr/lib/libboost_program_options.so.1.48.0 $tempdir/lib
cp -a /usr/lib/libboost_regex.so.1.48.0 $tempdir/lib
cp -a /usr/lib/libboost_system.so.1.48.0 $tempdir/lib
cp -a /usr/lib/libc-client.so.2007* $tempdir/lib
cp -a /usr/lib/libmcrypt.so.4* $tempdir/lib
cp -a /usr/lib/libmemcached.so.6* $tempdir/lib
cp -a /usr/lib/libonig.so.2* $tempdir/lib
cp -a /usr/lib/libtbb* $tempdir/lib
cp -a /usr/lib/libtcmalloc_minimal* $tempdir/lib
cp -a /usr/lib/libunwind* $tempdir/lib

mkdir $tempdir/lib/x86_64-linux-gnu
cp -a /usr/lib/x86_64-linux-gnu/libfontconfig.so.1* $tempdir/lib/x86_64-linux-gnu
cp -a /usr/lib/x86_64-linux-gnu/libgd.so.2* $tempdir/lib/x86_64-linux-gnu
cp -a /usr/lib/libicu*48* $tempdir/lib/x86_64-linux-gnu
cp -a /usr/lib/x86_64-linux-gnu/libjpeg.so.8* $tempdir/lib/x86_64-linux-gnu
cp -a /usr/lib/x86_64-linux-gnu/libXpm.so* $tempdir/lib/x86_64-linux-gnu

mkdir $tempdir/bin
cp /usr/bin/systemlib.php $tempdir/bin
cp /usr/bin/hhvm $tempdir/bin
cp /usr/bin/mlock $tempdir/bin/

tree $tempdir

echo "-----> Creating archive: hiphop-php-2.0.0.tar.gz"
tar --transform='s,^tmp/,,' -czf hiphop-php-2.0.0.tar.gz $tempdir/

echo "-----> Cleanup"
rm -rf $tempdir

#fontconfig-config hiphop-php libboost-filesystem1.48.0 libboost-program-options1.48.0 libboost-regex1.48.0 libboost-system1.48.0 libc-client2007e libfontconfig1
#  libgd2-xpm libicu48 libjpeg-turbo8 libjpeg8 libmcrypt4 libmemcached6 libonig2 